# Documentation: http://docs.travis-ci.com/user/languages/julia/
language: julia
os:
  - linux
  - osx
julia:
  - nightly
notifications:
  email: false
sudo: false
addons:
  apt:
    packages:
      - gfortran
      - libopenmpi-dev
      - openmpi-bin
before_install:
  - if [[ $(uname) == Darwin ]]; then brew update; brew install openmpi; fi
install:
  - julia -e 'Pkg.add("Coverage")'
before_script:
  - if [[ -a .git/shallow ]]; then git fetch --unshallow; fi
script:
  - julia -e 'Pkg.clone(pwd()); Pkg.build("FunHPC")'
  - julia --check-bounds=yes -e 'Pkg.test("FunHPC", coverage=true)'
  - mpirun -np 2 julia --check-bounds=yes -e 'Pkg.test("FunHPC", coverage=true)'
after_success:
  - julia -e 'cd(Pkg.dir("FunHPC")); using Coverage; Codecov.submit(process_folder())'
